services:
  hive-python:
    build:
      context: .
    container_name: hive_elt
    volumes:
      - ./scripts:/home/hadoop/scripts
      - ./conf:/home/hadoop/config
      - ./src:/home/hadoop/src
      - ./state_store:/home/hadoop/state_store
    working_dir: /home/hadoop/
    entrypoint: bash
    tty: true
    stdin_open: true
    networks:
      - hive_cluster_hnet
networks:
  hive_cluster_hnet:
    external: true