services:
  postgres:
    image: postgres:13
    container_name: airline_oltp
    hostname: airline_oltp
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: airline
      POSTGRES_PASSWORD: 123 
    ports:
      - "5444:5432"  
    volumes:
      - airline_db:/var/lib/postgresql/data  
    networks:
      - hive_cluster_hnet
networks:
  hive_cluster_hnet:
    external: true

volumes:
  airline_db: